schemaVersion: 2.3.0
metadata:
  generateName: devspaces-multicluster-redirector
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      memoryLimit: 6G
      memoryRequest: 512Mi
      cpuRequest: 1000m
      cpuLimit: 4000m
      mountSources: true
commands:
  - id: package
    exec:
      label: "1. Package"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        mvn clean package
      group:
        kind: build
        isDefault: true
  - id: deploy
    exec:
      label: "2. Deploy"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        kubectl apply -k openshift
  - id: cleanup
    exec:
      label: "3. Clean Up"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        kubectl delete -k openshift
