schemaVersion: 2.3.0
metadata:
  generateName: devspaces-multicluster-redirector
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      memoryLimit: 6G
      memoryRequest: 512Mi
      cpuRequest: 1000m
      cpuLimit: 4000m
      mountSources: true
commands:
  - id: package
    exec:
      label: "Package"
      component: tools
      commandLine: "mvn clean package -DskipTests=true"
      group:
        kind: build
        isDefault: true
  - id: runtests
    exec:
      label: "Run Tests"
      component: tools
      commandLine: "mvn test"
      group:
        kind: test
  - id: deploy
    exec:
      label: "Deploy"
      component: tools
      commandLine: "kubectl apply -k openshift -n redirector"
