apiVersion: v1
kind: ServiceAccount
metadata:
  name: devspaces-multicluster-redirector
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.primary: "https://your-multicluster-redirector-route-url/oauth/callback"
